version: '3.9'

services:
  sist2-admin:
    image: simon987/sist2:3.1.0-x64-linux
    restart: unless-stopped
    volumes:
      - ./data/sist2-data/:/sist2-admin/
      - /:/host
    ports:
      - 4090:4090 # sist2
      - 8080:8080 # sist2-admin
    working_dir: /root/sist2-admin/
    entrypoint: python3 /root/sist2-admin/sist2_admin/app.py

  monstache:
    hostname: monstache
    image: rwynn/monstache
    restart: always
    volumes:
      - ./monstache:/monstache-config-data/
    command: monstache -f ./monstache-config-data/config.toml