from datetime import datetime
from elasticsearch import Elasticsearch


# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "elastic"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="/Users/apple/Ragavan/Learning/E-Commerce/docker-compose/elastic-stack/es-certs/ca/ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())

doc = {
    'author': 'author_name',
    'text': 'Interensting content...',
    'timestamp': datetime.now(),
}
resp = client.index(index="test-index", id=1, document=doc)
print(resp['result'])