apiVersion: v1
kind: Service
metadata:
  name: {{ include "products-service.fullname" . }}
  labels:
    {{- include "products-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portname }}
      protocol: TCP
      name: {{ .Values.service.portname }}
  selector:
    {{- include "products-service.selectorLabels" . | nindent 4 }}
